test:
  adapter: test

production:
  adapter: solid_cable
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: study_buddy_production

# config/cable.yml
development:
  adapter: solid_cable
  silence_polling: true
